<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attributes' => '属性列表',
    'Models' => '模型列表',
    'Basic' => '基础',
    'Advance' => '高级',
    'Design' => '设计',
    'Create {modelClass}' => '新增 {modelClass}',
    'Update {modelClass}: ' => '更新 {modelClass}: ',
    'Create' => '新增',
    'Management' => '管理',
    'Model' => '模型',
    'Update' => '更新',
    'Attribute' => '属性',
];
